[ci]
runner = "ubuntu-24.04"
runtime = "nix"
provider = "actions"
platform = "github"
publish_crates = true
all_features = false

[ci.pages]
repo = "caniko/ronix"
canonical_domain = "ronix.tartanoglu.com"
